### ISSUE TITLE
🚀 Feature: CLI option to allow multiple ICAO codes at the same time

### ISSUE THREAD

**Issue by drph4nt0m** [drph4nt0m/avbot-charts#282]
### 🔖 Feature description

Should allow the ability to save multiple charts at the same time by passing commas separated ICAO codes like,

```sh
$ node app/main.js --icao VABB,KJFK
```

### 🎤 Pitch

Will allow the ability to scrape multiple but specific ICAO codes in a single command.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar feature request

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by PrBart** [comment]
I will take it.

Pls, assing it to me.

**Comment by drph4nt0m** [comment]
@PrBart assigned to you. All the best. 🚀
