### ISSUE TITLE
🚀 Feature: Allow a sub option under `all` to skip specific ICAO codes

### ISSUE THREAD

**Issue by drph4nt0m** [drph4nt0m/avbot-charts#284]
### 🔖 Feature description

Should allow the ability to skip multiple icao codes when running with `--all` flag

```sh
$ node app/main.js --all --skip-icao VABB,KJFK
```

### 🎤 Pitch

Will allow the ability to skip multiple but specific ICAO codes in the all command.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar feature request

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by NIKU-SINGH** [comment]
hey can I work on this and could you guide me on how can I make changes?

**Comment by drph4nt0m** [comment]
@NIKU-SINGH assigned to you. Check https://github.com/drph4nt0m/avbot-charts/issues/285 for reference. That issue is still a work in progress.

**Comment by drph4nt0m** [comment]
This issue is again up for grab.
