### ISSUE TITLE
🚀 Feature: Allow a sub option under `all` to skip specific countries

### ISSUE THREAD

**Issue by drph4nt0m** [drph4nt0m/avbot-charts#285]
### 🔖 Feature description

Should allow the ability to skip multiple countries when running with `--all` flag

```sh
$ node app/main.js --all --skip-country IN,US
```

### 🎤 Pitch

Will allow the ability to skip multiple but specific countries in the all command.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar feature request

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by siddhantdixit** [comment]
@drph4nt0m  I want to work on this issue. Can u assign this to me?

**Comment by drph4nt0m** [comment]
@siddhantdixit assigned to you. All the best. :rocket:
