### ISSUE TITLE
🚀 Feature: Only scan airport types with AIP available

### ISSUE THREAD

**Issue by dmarkowicz** [drph4nt0m/avbot-charts#286]
### 🔖 Feature description

It should allow to scan only selected airport types. Possible solutions:
- additional data in playbook file
- cli option to override playbook file defaults

### 🎤 Pitch

eAIP and AIP are most often available only for significant airports. Typically medium and large. The US even has data for heliports, but this is a beautiful exception. Bot try to scrap all airports from database. It takes a long time and can be improved. Bellow stats for `airports.csv` file: 
```bash
$ awk -F, '{print $3}' airports.csv | sort | uniq -c | sort -nr
  35934 "small_airport"
  14681 "heliport"
   6217 "closed"
   4534 "medium_airport"
   1050 "seaplane_base"
    620 "large_airport"
     35 "balloonport"
```
All airport types except `large_airport` and `medium_airport` can be skipped in most cases because there is no AIP for them. Types to be included should be checked by the author of the playbook for the first time. It could be hinted in playbook file. For example:
```json
{
  "scraper": {
    "include_type": ["large_airport", "medium_airport"]
  }
}
```

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar feature request

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by drph4nt0m** [comment]
Hey @dmarkowicz good suggestion. I was planning of hard coding it but this implementation looks much better. Let me know if you are planning to work on it and I will assign you the issue.

**Comment by dmarkowicz** [comment]
Please assign to me. I need to collect more data to find out if this is a good solution. Or maybe the distribution of AIP is completely random.

**Comment by drph4nt0m** [comment]
Sure. Assigned to you. All the best. 🚀
