### ISSUE TITLE
🚀 Feature: Add documentation for the playbook fields

### ISSUE THREAD

**Issue by drph4nt0m** [drph4nt0m/avbot-charts#292]
### 🔖 Feature description

Refer to the `app/engines/axios.js` and create a clear documentation for non-programmers' reference and to help them in contributing to the project. 

### 🎤 Pitch

The documentation should be in as simple words as possible so that a person with close to zero programming experience can also contribute to the project.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar feature request

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by nayan2306** [comment]
Can I do this please assign me the work

**Comment by drph4nt0m** [comment]
Hey @nayan2306 sorry but this task is taken by someone else. I forgot to assign it to them. You can check issues for more beginner friendly issues.

**Comment by nayan2306** [comment]
Okay sure
