### ISSUE TITLE
🚀 Feature: Add airport tests

### ISSUE THREAD

**Issue by drph4nt0m** [drph4nt0m/avbot-charts#300]
### 🔖 Feature description

Add tests for `getAirport.test.js`.

### 🎤 Pitch

In an earlier PR I accidentally mentioned that new tests are not needed in `getAirport.test.js`. I was thinking something else at that time and we actually do need country tests in `getAirport.test.js`. Would love if someone can add the tests for all the implemented playbooks.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar feature request

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by nmarulo** [comment]
Hello, I would like to try.

If I understood correctly, what to do is: 

based on what is already in the `getAirport.test.js` file, add the other records of the `airports.csv` file like this:

```javascript
test('Abu Dhabi', async () => {
  const icao = 'OM11';
  const airport = getAirport(icao);
  expect(airport).toMatchObject({ ident: 'OM11' });
});
```

and so for all records in the ident column of the csv file, correct?

**Comment by drph4nt0m** [comment]
Hey @nmarulo,
Yes you need to add tests similar to the ones already there in the `getAirport.test.js`. But the test name will not be the country name but the country 2 letter ISO code. 
And you just need to add tests for the countries for which playbook exists, check the `playbooks` directory.

**Comment by dmarkowicz** [comment]
You can use more compact syntax:
```js
test.each([
  ['AE', 'AE-0002'],
  ['AU', 'AGY'],
  ['XX', 'XXXX']
])('%s', async (country, icao) => {
  const airport = getAirport(icao);
  expect(airport).toMatchObject({ iso_country: country, ident: icao });
});
```
