### ISSUE TITLE
🚀 Feature: Add support for custom headers in axios engine

### ISSUE THREAD

**Issue by drph4nt0m** [drph4nt0m/avbot-charts#310]
### 🔖 Feature description

Some AIPs need some specific headers in the requests and a custom header support might be helpful in the long run.

### 🎤 Pitch

We can have a separate field for custom headers under the features key

```json
{
  "features": {
    "headers:": ["header:value", "header2:value"],
  }
}
```

The feature should be backward compatible with playbook which don't need this.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar feature request

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by zinovik** [comment]
I would like to work on it!
