### ISSUE TITLE
🚀 Feature: Distributed log files

### ISSUE THREAD

**Issue by drph4nt0m** [drph4nt0m/avbot-charts#317]
### 🔖 Feature description

This feature is only for saving logs to files. The winston logging on console should work as it currently does.

Split the logs for each run into multiple files. For example, the log files created when ran `node ./app/main.js -c IN,US` would be

- `logs/<timestamp_of_program_run>.log`
- `logs/<timestamp_of_program_run>_IN.log`
- `logs/<timestamp_of_program_run>_US.log`

`timestamp_of_program_run` will be same for all 3 files and it will be set once the program is started.

### 🎤 Pitch

Currently the winston logs everything to one log file per run. It would be great if the log file can be further split based countries for each run. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/drph4nt0m/avbot-charts/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by koshimagoyal** [comment]
@drph4nt0m have fixed issue. Please review and merge PR.

**Comment by drph4nt0m** [comment]
The issue is again up for grab.
