### ISSUE TITLE
🚀 Feature: Add a cli command to get list of disabled playbooks

### ISSUE THREAD

**Issue by drph4nt0m** [drph4nt0m/avbot-charts#353]
### 🔖 Feature description

Add CLI option `list-disabled` with alias `ld`.

Usage:
`node ./app/main.js --list-disabled` or `node ./app/main.js -ld`

This option to read all playbooks and list out all disabled playbooks. 

### 🎤 Pitch

Currently, disabled playbooks require manual tracking. This command will make it easy to just list all disabled playbooks in one go and then someone can check if they can be updated and enabled again.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/drph4nt0m/avbot-charts/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by nguyenhung15913** [comment]
Can I work on this issue ?

**Comment by drph4nt0m** [comment]
@nguyenhung15913 assigned to you. All the best! 🚀

**Comment by nguyenhung15913** [comment]
Hi, I have sent you another pull request .
